### ISSUE TITLE
Don't show anything if there is no site in a specific language (custom navigation)

### ISSUE THREAD

**Issue by GMTeams** [inspiredminds/contao-language-autoswitch#1]
I have the result, that if there are no sites in a specific language (but in the fallback language), the frontend module "custom navigation" shows instead parent/sibling sites.

Was this intended? Is there a possibility that I can hide these sites, so that the module doesn't show anything?
This seems only to occur in the "custom navigation" - when I'm testing this in a "navigation" there are no sites shown instead.

Thank you very much, this plugin helped me a lot to save on not necessary frontend modules.

**Comment by fritzmg** [comment]
This extension has no influence on the navigation modules. The purpose of this extension is to automatically redirect to the language that the visitor last used. Usually Contao would redirect to the browser's language or the fallback language.

**Comment by GMTeams** [comment]
Thank you very much for your fast answer. Now it's clear to me that the problem has nothing to do with this plugin.
