### ISSUE TITLE
Fresh install on Contao 5.2.4 throws Fatal exception due to symphony compatibility

### ISSUE THREAD

**Issue by cc-ben** [inspiredminds/contao-language-autoswitch#2]
Hi, in a fresh instance of latest Contao 5.2.4 with no other modules installed the contao-language-autoswitch throws the following exception

```Fatal error: Declaration of InspiredMinds\ContaoLanguageAutoswitch\ContaoLanguageAutoswitch::getPath() must be compatible with Symfony\Component\HttpKernel\Bundle\Bundle::getPath(): string in /www/htdocs/[...]/[...]/live/vendor/inspiredminds/contao-language-autoswitch/src/ContaoLanguageAutoswitch.php on line 15```

the dry run was successfull though.

Maybe you can get a look into this. If you need any further information, please let me know.

Regards
Ben

**Comment by fritzmg** [comment]
Fixed in c80523e32ae912f06581fedfc383b818d8b1572e
